version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=SPM_db
      - DB_USER=postgres
      - DB_PASSWORD=admin123
      - JWT_SECRET=your_super_secret_jwt_key_here
      - JWT_EXPIRES_IN=7d
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=spmprojectb@gmail.com
      - EMAIL_PASS=rgul ahdh caze hizj
    volumes:
      - ./backend/uploads:/app/uploads

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: SPM_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/triggers.sql:/docker-entrypoint-initdb.d/2-triggers.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/3-seed.sql

volumes:
  postgres_data:
